/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Ha Thach (tinyusb.org)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */

#include "tusb.h"
#include "usb_descriptors.h"
#include <stm32h7xx_hal.h>
#include <string.h>
#include <stdio.h>

/* A combination of interfaces must have a unique product id, since PC will save
 * device driver after the first plug. Same VID/PID with different interface e.g
 * MSC (first), then CDC (later) will possibly cause system error on PC.
 *
 * Auto ProductID layout's Bitmap:
 *   [MSB]         HID | MSC | CDC          [LSB]
 */
#define _PID_MAP(itf, n) ((CFG_TUD_##itf) << (n))

// This is autogenerated from the tinyusb conf file
// TODO: if a specific PID is required this should be hardcoded instead
#define USB_PID                                                      \
    (0x4000 | _PID_MAP(CDC, 0) | _PID_MAP(MSC, 1) | _PID_MAP(HID, 2) \
     | _PID_MAP(MIDI, 3) | _PID_MAP(VENDOR, 4))

// This is the STM VID - same as Daisy uses
#define USB_VID 1155

// USB 1.1 - best Daisy can do (no 2.0 PHY)
#define USB_BCD 0x0110

//--------------------------------------------------------------------+
// Device Descriptors
//--------------------------------------------------------------------+
tusb_desc_device_t const desc_device
    = {.bLength         = sizeof(tusb_desc_device_t),
       .bDescriptorType = TUSB_DESC_DEVICE,
       .bcdUSB          = USB_BCD,

       // Use Interface Association Descriptor (IAD) for CDC
       // As required by USB Specs IAD's subclass must be common class (2) and
       // protocol must be IAD (1)
       .bDeviceClass    = TUSB_CLASS_MISC,
       .bDeviceSubClass = MISC_SUBCLASS_COMMON,
       .bDeviceProtocol = MISC_PROTOCOL_IAD,
       .bMaxPacketSize0 = CFG_TUD_ENDPOINT0_SIZE,

       .idVendor  = USB_VID,
       .idProduct = USB_PID,
       .bcdDevice = 0x0100,

       .iManufacturer = 0x01,
       .iProduct      = 0x02,
       .iSerialNumber = 0x03,

       .bNumConfigurations = 0x01};

// Invoked when received GET DEVICE DESCRIPTOR
// Application return pointer to descriptor
uint8_t const *tud_descriptor_device_cb(void)
{
    return (uint8_t const *)&desc_device;
}

//--------------------------------------------------------------------+
// Configuration Descriptor
//--------------------------------------------------------------------+
#define CONFIG_TOTAL_LEN \
    (TUD_CONFIG_DESC_LEN + CFG_TUD_CDC * TUD_CDC_DESC_LEN + TUD_MIDI_DESC_LEN)

// These can all kinda just be whatever I think,
// as long as they're unique and midi and audio i/o
// are using the same byte
#define EPNUM_CDC_NOTIF 0x81
#define EPNUM_CDC_OUT 0x02
#define EPNUM_MIDI_OUT 0x04

uint8_t const desc_configuration_default[] = {
    // Config number, interface count, string index, total length, attribute,
    // power in mA
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_TOTAL_LEN, 0x00, 100),

    // // Interface number, string index, EP out & EP In Address, EP SIze
    TUD_MIDI_DESCRIPTOR(ITF_NUM_MIDI,
                        4,
                        EPNUM_MIDI_OUT,
                        (0x80 | EPNUM_MIDI_OUT),
                        64),
    // 1st CDC: Interface number, string index, EP notification address and
    // size, EP data address (out, in) and size.
    TUD_CDC_DESCRIPTOR(ITF_NUM_CDC,
                       5,
                       EPNUM_CDC_NOTIF,
                       8,
                       EPNUM_CDC_OUT,
                       (0x80 | EPNUM_CDC_OUT),
                       64),

};

// Invoked when received GET CONFIGURATION DESCRIPTOR
// Application return pointer to descriptor
// Descriptor contents must exist long enough for transfer to complete
uint8_t const *tud_descriptor_configuration_cb(uint8_t index)
{
    (void)index; // for multiple configurations
    return desc_configuration_default;
}

//--------------------------------------------------------------------+
// String Descriptors
//--------------------------------------------------------------------+

// String Descriptor Index
enum
{
    STRID_LANGID = 0,
    STRID_MANUFACTURER,
    STRID_PRODUCT,
    STRID_SERIAL,
};

// array of pointer to string descriptors
char const *string_desc_arr[] = {
    (const char[]){0x09, 0x04}, // 0: is supported language is English (0x0409)
    "Neo Instruments",          // 1: Manufacturer
    "Ventilator 3",             // 2: Product
    NULL,                       // 3: Serials will use unique ID if possible
    "Ventilator 3 MIDI",        // 4: MIDI Interface
    "Ventilator 3 Serial",      // 5: CDC Interface
};

static inline size_t board_usb_get_serial(uint16_t desc_str1[],
                                          size_t   max_chars)
{
    char buf[32];
    // Sum the uid words as a pseudo unique serial ID for USB desc
    uint32_t uid = 0;
    uid += HAL_GetUIDw0();
    uid += HAL_GetUIDw1();
    uid += HAL_GetUIDw2();

    size_t len = 0;
    if(uid != 0)
    {
        len = snprintf(buf, max_chars, "%u", (unsigned int)uid) / 2;
    }
    return len > max_chars ? max_chars : len;
}

static char     _serial_str[32];
static uint16_t _desc_str[32 + 1];

// Invoked when received GET STRING DESCRIPTOR request
// Application return pointer to descriptor, whose contents must exist long
// enough for transfer to complete
uint16_t const *tud_descriptor_string_cb(uint8_t index, uint16_t langid)
{
    (void)langid;
    size_t chr_count;

    switch(index)
    {
        case STRID_LANGID:
            memcpy(&_desc_str[1], string_desc_arr[0], 2);
            chr_count = 1;
            break;

        default:
            // Note: the 0xEE index string is a Microsoft OS 1.0 Descriptors.
            // https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/microsoft-defined-usb-descriptors

            if(!(index < sizeof(string_desc_arr) / sizeof(string_desc_arr[0])))
                return NULL;

            const char *str = string_desc_arr[index];

            if(index == STRID_SERIAL)
            {
                // Sum the uid words as a pseudo unique serial ID for USB desc
                uint32_t uid = 0;
                uid += HAL_GetUIDw0();
                uid += HAL_GetUIDw1();
                uid += HAL_GetUIDw2();

                if(uid != 0)
                {
                    sprintf(_serial_str, "%u", (unsigned int)uid);
                    str = _serial_str;
                }
            }

            // Cap at max char
            chr_count = (uint8_t)strlen(str);
            if(chr_count > 31)
                chr_count = 31;

            // Convert ASCII string into UTF-16
            for(uint8_t i = 0; i < chr_count; i++)
            {
                _desc_str[1 + i] = str[i];
            }
    }

    // first byte is length (including header), second byte is string type
    _desc_str[0] = (uint16_t)((TUSB_DESC_STRING << 8) | (2 * chr_count + 2));

    return _desc_str;
}
